### PR TITLE
remove redundant error and warning declarations

### PR DESCRIPTION
**Pull request by christophidesp**
Remove redundant error and warning declarations
Update dropdown color for dark theme to differentiate it from borders

### CODE REVIEW

**Review by burbuli8ra — COMMENTED** [review]
Same tests are failing!
Please lets fix them before merging this PR! 😄

**Review by jacekkolasa — CHANGES_REQUESTED** [review]
Sorry @christophidesp but those colors are used in dashboard! We would need to fix it in there, first.
(Also perhaps in cloud-iframes, but i'm not sure, need to check). I can help you with it

**Comment by christophidesp** [comment]
@jacekkolasa they were already declared some lines above, so we had duplicate declarations for error and warning.

**Review by jacekkolasa — APPROVED** [review]
@christophidesp didn't noticed it! Thanks :)

**Pull request merged**
